### ISSUE TITLE
undefined

### ISSUE THREAD

**Issue by nk932714** [hemanth/xkcd-img#3]
when opening demo it is displaying undefined

**Comment by hemanth** [comment]
`polymer-xhr.html:64 Mixed Content: The page at 'https://h3manth.com/demo/custom-elements/xkcd-img/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://xkcd-imgs.herokuapp.com/'. This request has been blocked; the content must be served over HTTPS.`

**Comment by nk932714** [comment]
@hemanth thanks
